// Config for Flexbox
var flexbox = {
  alItms: 'alignItems',
  alSf: 'alignSelf',
  bBtW: 'borderBottomWidth',
  bLW: 'borderLeftWidth',
  bRW: 'borderRightWidth',
  bTW: 'borderTopWidth',
  bW: 'borderWidth',
  bt: 'bottom',
  fl: 'flex',
  flD: 'flexDirection',
  flW: 'flexWrap',
  ht: 'height',
  jCt: 'justifyContent',
  lt: 'left',
  mg: 'margin',
  mgB: 'marginBottom',
  mgH: 'marginHorizontal',
  mgL: 'marginLeft',
  mgR: 'marginRight',
  mgT: 'marginTop',
  mgV: 'marginVertical',
  mxH: 'maxHeight',
  mxW: 'maxWidth',
  mnH: 'minHeight',
  mnW: 'minWidth',
  pd: 'padding',
  pdB: 'paddingBottom',
  pdH: 'paddingHorizontal',
  pdL: 'paddingLeft',
  pdR: 'paddingRight',
  pdT: 'paddingTop',
  pdV: 'paddingVertical',
  ps: 'position',
  rt: 'right',
  t: 'top',
  w: 'width',
  zIdx: 'zIndex'  
};

module.exports = flexbox;